[2023-04-24T16:12:24.224] [DEBUG] default - 服务启动成功
[2023-04-24T16:49:56.752] [DEBUG] default - 服务启动成功
[2023-04-24T16:50:38.209] [DEBUG] default - 服务启动成功
[2023-04-24T16:55:25.509] [DEBUG] default - 服务启动成功
[2023-04-24T16:55:43.454] [DEBUG] default - 服务启动成功
[2023-04-24T16:56:07.762] [DEBUG] default - 服务启动成功
[2023-04-24T17:03:58.127] [DEBUG] default - 服务启动成功
[2023-04-24T17:04:00.579] [DEBUG] default - 服务启动成功
[2023-04-24T17:04:38.629] [DEBUG] default - 未知错误 D:\personal\personal-projects\financial\server\src\models\fund\idnex.js:32
  fundnetworth:Object//基金净值
  ^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (D:\personal\personal-projects\financial\server\src\mapper\investment\index.js:10:14)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
[2023-04-24T17:04:55.360] [DEBUG] default - 未知错误 D:\personal\personal-projects\financial\server\src\models\fund\idnex.js:32
  fundnetworth:Object//基金净值
  ^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (D:\personal\personal-projects\financial\server\src\mapper\investment\index.js:10:14)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
[2023-04-24T17:27:21.800] [DEBUG] default - 服务启动成功
[2023-04-24T17:27:38.855] [DEBUG] default - 未知错误 D:\personal\personal-projects\financial\server\src\models\fund\idnex.js:32
  fundnetworth:Object//基金净值
  ^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (D:\personal\personal-projects\financial\server\src\mapper\investment\index.js:10:14)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
[2023-04-24T17:28:30.038] [DEBUG] default - 未知错误 D:\personal\personal-projects\financial\server\src\models\fund\idnex.js:32
  fundnetworth:Object//基金净值
  ^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (D:\personal\personal-projects\financial\server\src\mapper\investment\index.js:10:14)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
[2023-04-24T17:29:29.585] [DEBUG] default - 服务启动成功
[2023-04-24T17:29:31.907] [DEBUG] default - 服务启动成功
[2023-04-24T17:40:01.057] [DEBUG] default - 服务启动成功
[2023-04-24T17:40:05.367] [DEBUG] default - 服务启动成功
[2023-04-24T17:40:08.024] [DEBUG] default - 服务启动成功
[2023-04-24T17:43:05.693] [DEBUG] default - 服务启动成功
[2023-04-24T17:43:09.107] [DEBUG] default - 服务启动成功
[2023-04-24T17:45:31.430] [DEBUG] default - 服务启动成功
[2023-04-24T17:45:34.359] [DEBUG] default - 服务启动成功
[2023-04-24T18:05:00.020] [DEBUG] default - 服务启动成功
[2023-04-24T18:05:43.029] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (D:\personal\personal-projects\financial\server\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:66:26)
    at async cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:9) {
  originalError: TokenExpiredError: jwt expired
      at D:\personal\personal-projects\financial\server\node_modules\jsonwebtoken\verify.js:190:21
      at getSecret (D:\personal\personal-projects\financial\server\node_modules\jsonwebtoken\verify.js:97:14)
      at module.exports [as verify] (D:\personal\personal-projects\financial\server\node_modules\jsonwebtoken\verify.js:101:10)
      at D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\verify.js:5:13
      at new Promise (<anonymous>)
      at module.exports (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\verify.js:4:12)
      at D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:38:64
      at Array.map (<anonymous>)
      at jwt (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:38:43)
      at D:\personal\personal-projects\financial\server\node_modules\koa-unless\index.js:29:12 {
    expiredAt: 2023-04-11T17:44:09.000Z
  }
}
[2023-04-24T18:06:31.191] [DEBUG] default - 服务启动成功
[2023-04-24T18:06:36.787] [DEBUG] default - 未知错误 ReferenceError: fraction is not defined
    at module.exports (D:\personal\personal-projects\financial\server\src\service\investment\editfundinfo.js:16:11)
    at module.exports (D:\personal\personal-projects\financial\server\src\controller\investment\editfundinfo.js:21:22)
    at D:\personal\personal-projects\financial\server\src\router\investment\index.js:28:52
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at D:\personal\personal-projects\financial\server\node_modules\@koa\router\lib\router.js:425:16
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:34:12
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\@koa\router\lib\router.js:430:31)
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at bodyParser (D:\personal\personal-projects\financial\server\node_modules\koa-bodyparser\index.js:95:11)
[2023-04-24T18:06:48.351] [DEBUG] default - 服务启动成功
[2023-04-24T18:06:52.813] [DEBUG] default - 服务启动成功
[2023-04-24T18:12:04.612] [DEBUG] default - 服务启动成功
[2023-04-24T18:18:09.622] [DEBUG] default - 服务启动成功
[2023-04-24T18:18:11.927] [DEBUG] default - 服务启动成功
[2023-04-24T18:18:31.106] [DEBUG] default - 服务启动成功
[2023-04-24T18:18:52.485] [DEBUG] default - 服务启动成功
[2023-04-24T18:19:53.440] [DEBUG] default - 服务启动成功
[2023-04-24T18:19:57.939] [DEBUG] default - 服务启动成功
[2023-04-24T18:23:51.260] [DEBUG] default - 服务启动成功
[2023-04-24T18:24:28.820] [DEBUG] default - 服务启动成功
[2023-04-24T18:24:30.576] [DEBUG] default - 服务启动成功
[2023-04-24T18:24:58.603] [DEBUG] default - 服务启动成功
[2023-04-24T18:25:32.829] [DEBUG] default - 服务启动成功
[2023-04-24T18:25:35.058] [DEBUG] default - 服务启动成功
[2023-04-24T18:32:35.588] [DEBUG] default - 服务启动成功
[2023-04-25T14:10:39.981] [DEBUG] default - 服务启动成功
[2023-05-05T11:03:21.293] [DEBUG] default - 服务启动成功
[2023-05-05T11:03:23.518] [DEBUG] default - code:401 UnauthorizedError: Bad Authorization header format. Format is "Authorization: Bearer <token>"
    at Object.throw (D:\personal\personal-projects\financial\server\node_modules\koa\lib\context.js:97:11)
    at resolveAuthorizationHeader (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\resolvers\auth-header.js:26:18)
    at D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:20:49
    at Array.find (<anonymous>)
    at jwt (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:20:24)
    at D:\personal\personal-projects\financial\server\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:15)
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:34:12
[2023-05-05T11:03:23.552] [DEBUG] default - 未知错误 Error: 方法没有实现
    at Object.methodNotAllowed (D:\personal\personal-projects\financial\server\src\router\index.js:46:40)
    at D:\personal\personal-projects\financial\server\node_modules\@koa\router\lib\router.js:520:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async bodyParser (D:\personal\personal-projects\financial\server\node_modules\koa-bodyparser\index.js:95:5)
    at async cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:9) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 405,
    payload: { statusCode: 405, error: 'Method Not Allowed', message: '方法没有实现' },
    headers: {}
  }
}
[2023-05-05T11:03:23.774] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (D:\personal\personal-projects\financial\server\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\personal\personal-projects\financial\server\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:15)
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:34:12
    at Application.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:182:12)
    at Server.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:157:19)
    at Server.emit (node:events:513:28)
[2023-05-05T11:03:29.109] [DEBUG] default - 未知错误 Error: 方法没有实现
    at Object.methodNotAllowed (D:\personal\personal-projects\financial\server\src\router\index.js:46:40)
    at D:\personal\personal-projects\financial\server\node_modules\@koa\router\lib\router.js:520:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async bodyParser (D:\personal\personal-projects\financial\server\node_modules\koa-bodyparser\index.js:95:5)
    at async cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:9) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 405,
    payload: { statusCode: 405, error: 'Method Not Allowed', message: '方法没有实现' },
    headers: {}
  }
}
[2023-05-05T11:03:29.323] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (D:\personal\personal-projects\financial\server\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\personal\personal-projects\financial\server\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:15)
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:34:12
    at Application.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:182:12)
    at Server.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:157:19)
    at Server.emit (node:events:513:28)
[2023-05-05T11:03:31.642] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (D:\personal\personal-projects\financial\server\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\personal\personal-projects\financial\server\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:15)
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:34:12
    at Application.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:182:12)
    at Server.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:157:19)
    at Server.emit (node:events:513:28)
[2023-05-05T11:03:33.346] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (D:\personal\personal-projects\financial\server\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\personal\personal-projects\financial\server\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:15)
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:34:12
    at Application.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:182:12)
    at Server.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:157:19)
    at Server.emit (node:events:513:28)
[2023-05-05T11:03:34.204] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (D:\personal\personal-projects\financial\server\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\personal\personal-projects\financial\server\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:15)
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:34:12
    at Application.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:182:12)
    at Server.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:157:19)
    at Server.emit (node:events:513:28)
[2023-05-05T11:03:34.449] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (D:\personal\personal-projects\financial\server\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\personal\personal-projects\financial\server\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:15)
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:34:12
    at Application.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:182:12)
    at Server.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:157:19)
    at Server.emit (node:events:513:28)
[2023-05-05T11:03:35.679] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (D:\personal\personal-projects\financial\server\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\personal\personal-projects\financial\server\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:15)
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:34:12
    at Application.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:182:12)
    at Server.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:157:19)
    at Server.emit (node:events:513:28)
[2023-05-05T11:03:35.899] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (D:\personal\personal-projects\financial\server\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\personal\personal-projects\financial\server\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:15)
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:34:12
    at Application.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:182:12)
    at Server.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:157:19)
    at Server.emit (node:events:513:28)
[2023-05-05T11:05:31.248] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (D:\personal\personal-projects\financial\server\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\personal\personal-projects\financial\server\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:15)
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:34:12
    at Application.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:182:12)
    at Server.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:157:19)
    at Server.emit (node:events:513:28)
[2023-05-05T11:05:31.427] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (D:\personal\personal-projects\financial\server\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\personal\personal-projects\financial\server\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:15)
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:34:12
    at Application.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:182:12)
    at Server.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:157:19)
    at Server.emit (node:events:513:28)
[2023-05-05T11:05:38.094] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (D:\personal\personal-projects\financial\server\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\personal\personal-projects\financial\server\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:15)
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:34:12
    at Application.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:182:12)
    at Server.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:157:19)
    at Server.emit (node:events:513:28)
[2023-05-05T11:05:38.344] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (D:\personal\personal-projects\financial\server\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\personal\personal-projects\financial\server\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:15)
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:34:12
    at Application.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:182:12)
    at Server.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:157:19)
    at Server.emit (node:events:513:28)
[2023-05-05T11:05:39.764] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (D:\personal\personal-projects\financial\server\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\personal\personal-projects\financial\server\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:15)
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:34:12
    at Application.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:182:12)
    at Server.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:157:19)
    at Server.emit (node:events:513:28)
[2023-05-05T11:05:40.111] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (D:\personal\personal-projects\financial\server\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\personal\personal-projects\financial\server\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\personal\personal-projects\financial\server\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at cors (D:\personal\personal-projects\financial\server\node_modules\koa2-cors\dist\index.js:91:15)
    at dispatch (D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:42:32)
    at D:\personal\personal-projects\financial\server\node_modules\koa-compose\index.js:34:12
    at Application.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:182:12)
    at Server.handleRequest (D:\personal\personal-projects\financial\server\node_modules\koa\lib\application.js:157:19)
    at Server.emit (node:events:513:28)
[2023-05-05T11:06:12.510] [DEBUG] default - 服务启动成功
[2023-05-05T11:18:52.686] [DEBUG] default - 服务启动成功
[2023-05-05T11:18:55.458] [DEBUG] default - 服务启动成功
[2023-05-05T11:19:33.116] [DEBUG] default - 服务启动成功
[2023-05-05T11:19:42.709] [DEBUG] default - 服务启动成功
[2023-05-05T11:20:36.237] [DEBUG] default - 服务启动成功
[2023-05-05T11:20:38.280] [DEBUG] default - 服务启动成功
[2023-05-05T11:20:58.422] [DEBUG] default - 服务启动成功
[2023-05-05T11:21:06.277] [DEBUG] default - 服务启动成功
[2023-05-05T11:21:14.577] [DEBUG] default - 服务启动成功
[2023-05-05T13:06:44.446] [DEBUG] default - 服务启动成功
