[2023-03-16T21:20:48.583] [DEBUG] default - 服务启动成功
[2023-03-16T21:21:05.713] [DEBUG] default - 服务启动成功
[2023-03-16T21:26:01.572] [DEBUG] default - 服务启动成功
[2023-03-16T21:47:48.810] [DEBUG] default - 服务启动成功
[2023-03-16T21:48:04.289] [DEBUG] default - 服务启动成功
[2023-03-16T21:48:57.347] [DEBUG] default - 服务启动成功
[2023-03-16T21:49:52.235] [DEBUG] default - 未知错误 Error: 方法没有实现
    at Object.methodNotAllowed (/Users/hanhongguang/Documents/个人项目/Financial/src/router/index.js:46:40)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:520:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 405,
    payload: { statusCode: 405, error: 'Method Not Allowed', message: '方法没有实现' },
    headers: {}
  }
}
[2023-03-16T21:51:06.874] [DEBUG] default - 未知错误 Error: 方法没有实现
    at Object.methodNotAllowed (/Users/hanhongguang/Documents/个人项目/Financial/src/router/index.js:46:40)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:520:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 405,
    payload: { statusCode: 405, error: 'Method Not Allowed', message: '方法没有实现' },
    headers: {}
  }
}
[2023-03-16T21:52:17.734] [DEBUG] default - 服务启动成功
[2023-03-16T21:52:23.533] [DEBUG] default - 服务启动成功
[2023-03-16T21:52:45.003] [DEBUG] default - 服务启动成功
[2023-03-16T21:52:48.190] [DEBUG] default - 服务启动成功
[2023-03-16T21:52:52.272] [DEBUG] default - 服务启动成功
[2023-03-16T21:52:58.764] [DEBUG] default - 服务启动成功
[2023-03-16T21:53:09.687] [DEBUG] default - 服务启动成功
[2023-03-16T21:53:46.628] [DEBUG] default - 服务启动成功
[2023-03-16T21:55:12.691] [DEBUG] default - 服务启动成功
[2023-03-16T21:55:28.104] [DEBUG] default - 服务启动成功
[2023-03-16T21:58:29.628] [DEBUG] default - 未知错误 Error: 方法没有实现
    at Object.methodNotAllowed (/Users/hanhongguang/Documents/个人项目/Financial/src/router/index.js:46:40)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:520:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 405,
    payload: { statusCode: 405, error: 'Method Not Allowed', message: '方法没有实现' },
    headers: {}
  }
}
[2023-03-16T21:59:45.374] [DEBUG] default - 未知错误 Error: 方法没有实现
    at Object.methodNotAllowed (/Users/hanhongguang/Documents/个人项目/Financial/src/router/index.js:46:40)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:520:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 405,
    payload: { statusCode: 405, error: 'Method Not Allowed', message: '方法没有实现' },
    headers: {}
  }
}
[2023-03-16T21:59:47.479] [DEBUG] default - 未知错误 Error: 方法没有实现
    at Object.methodNotAllowed (/Users/hanhongguang/Documents/个人项目/Financial/src/router/index.js:46:40)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:520:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 405,
    payload: { statusCode: 405, error: 'Method Not Allowed', message: '方法没有实现' },
    headers: {}
  }
}
[2023-03-16T21:59:52.059] [DEBUG] default - 未知错误 Error: 方法没有实现
    at Object.methodNotAllowed (/Users/hanhongguang/Documents/个人项目/Financial/src/router/index.js:46:40)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:520:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 405,
    payload: { statusCode: 405, error: 'Method Not Allowed', message: '方法没有实现' },
    headers: {}
  }
}
[2023-03-16T22:02:41.293] [DEBUG] default - 服务启动成功
[2023-03-16T22:04:12.025] [DEBUG] default - 服务启动成功
[2023-03-16T22:04:12.364] [DEBUG] default - 服务启动成功
[2023-03-16T22:04:12.719] [DEBUG] default - 服务启动成功
[2023-03-16T22:04:32.192] [DEBUG] default - 服务启动成功
[2023-03-16T22:05:54.746] [DEBUG] default - 服务启动成功
[2023-03-16T22:06:35.104] [DEBUG] default - 服务启动成功
[2023-03-16T22:12:29.852] [DEBUG] default - 服务启动成功
[2023-03-16T22:13:49.729] [DEBUG] default - 服务启动成功
[2023-03-16T22:14:10.353] [DEBUG] default - 服务启动成功
[2023-03-16T22:14:33.989] [DEBUG] default - 服务启动成功
[2023-03-16T22:14:51.064] [DEBUG] default - 服务启动成功
[2023-03-16T22:14:51.322] [DEBUG] default - 服务启动成功
[2023-03-16T22:15:01.653] [DEBUG] default - 服务启动成功
[2023-03-16T22:17:08.747] [DEBUG] default - 服务启动成功
[2023-03-16T22:17:09.441] [DEBUG] default - 服务启动成功
[2023-03-16T22:18:58.949] [DEBUG] default - 服务启动成功
[2023-03-16T22:19:27.806] [DEBUG] default - 服务启动成功
[2023-03-16T22:20:39.116] [DEBUG] default - 服务启动成功
[2023-03-16T22:21:21.640] [DEBUG] default - 服务启动成功
[2023-03-16T22:21:58.453] [DEBUG] default - 服务启动成功
[2023-03-16T22:22:54.959] [DEBUG] default - 服务启动成功
[2023-03-16T22:23:22.745] [DEBUG] default - 服务启动成功
[2023-03-16T22:23:23.024] [DEBUG] default - 服务启动成功
[2023-03-16T22:25:34.245] [DEBUG] default - 服务启动成功
[2023-03-16T22:27:16.859] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa/lib/context.js:97:11)
    at jwt (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:66:26)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9) {
  originalError: TokenExpiredError: jwt expired
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:190:21
      at getSecret (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:97:14)
      at Object.module.exports [as verify] (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:101:10)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/verify.js:5:13
      at new Promise (<anonymous>)
      at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/verify.js:4:12)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:38:64
      at Array.map (<anonymous>)
      at jwt (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:38:43)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-unless/index.js:29:12 {
    expiredAt: 2023-03-15T19:45:40.000Z
  }
}
[2023-03-16T22:27:59.106] [DEBUG] default - 未知错误 ReferenceError: reqiure is not defined
    at Object.<anonymous> (/Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/newfinancialrecord.js:9:32)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/hanhongguang/Documents/个人项目/Financial/src/controller/budget/newfinancialrecord.js:9:15)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
[2023-03-16T22:28:43.810] [DEBUG] default - 服务启动成功
[2023-03-16T22:28:43.996] [DEBUG] default - 未知错误 TypeError: Invalid schema configuration: `type` schematype definition is invalid. See https://mongoosejs.com/docs/guide.html#definition for more info on supported schema syntaxes.
    at Schema.interpretAsType (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/mongoose/lib/schema.js:1335:11)
    at Schema.path (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/mongoose/lib/schema.js:963:27)
    at Schema.add (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/mongoose/lib/schema.js:634:12)
    at new Schema (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/mongoose/lib/schema.js:133:10)
    at Object.<anonymous> (/Users/hanhongguang/Documents/个人项目/Financial/src/models/bills/index.js:10:15)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
[2023-03-16T22:29:52.728] [DEBUG] default - 服务启动成功
[2023-03-16T22:30:23.755] [DEBUG] default - 服务启动成功
[2023-03-16T22:31:26.591] [DEBUG] default - 服务启动成功
[2023-03-16T22:32:35.796] [DEBUG] default - 服务启动成功
[2023-03-16T22:33:10.447] [DEBUG] default - 服务启动成功
[2023-03-16T22:33:40.669] [DEBUG] default - 服务启动成功
[2023-03-16T22:34:48.052] [DEBUG] default - 服务启动成功
[2023-03-16T22:35:47.258] [DEBUG] default - 服务启动成功
[2023-03-16T22:44:00.198] [DEBUG] default - 服务启动成功
[2023-03-16T22:48:14.670] [DEBUG] default - 服务启动成功
[2023-03-16T22:48:55.590] [DEBUG] default - 服务启动成功
[2023-03-16T22:52:27.720] [DEBUG] default - 服务启动成功
[2023-03-16T22:53:28.738] [DEBUG] default - 服务启动成功
[2023-03-16T22:55:55.559] [DEBUG] default - 服务启动成功
[2023-03-16T22:56:21.194] [DEBUG] default - 服务启动成功
[2023-03-16T22:56:49.927] [DEBUG] default - 服务启动成功
[2023-03-16T22:56:59.633] [DEBUG] default - 服务启动成功
[2023-03-16T23:00:09.244] [DEBUG] default - 服务启动成功
[2023-03-16T23:00:34.569] [DEBUG] default - 服务启动成功
[2023-03-16T23:01:30.296] [DEBUG] default - 未知错误 ReferenceError: getIncome is not defined
    at Object.<anonymous> (/Users/hanhongguang/Documents/个人项目/Financial/src/mapper/income/index.js:31:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/hanhongguang/Documents/个人项目/Financial/src/service/income/getincometypelist.js:1:31)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
[2023-03-16T23:02:36.123] [DEBUG] default - 未知错误 ReferenceError: getIncome is not defined
    at Object.<anonymous> (/Users/hanhongguang/Documents/个人项目/Financial/src/mapper/income/index.js:31:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/hanhongguang/Documents/个人项目/Financial/src/service/income/getincometypelist.js:1:31)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
[2023-03-16T23:02:49.432] [DEBUG] default - 未知错误 ReferenceError: getIncome is not defined
    at Object.<anonymous> (/Users/hanhongguang/Documents/个人项目/Financial/src/mapper/income/index.js:31:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/hanhongguang/Documents/个人项目/Financial/src/service/income/newincometype.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
[2023-03-16T23:03:17.771] [DEBUG] default - 服务启动成功
[2023-03-16T23:04:55.514] [DEBUG] default - 服务启动成功
[2023-03-16T23:06:00.326] [DEBUG] default - 服务启动成功
[2023-03-16T23:06:11.725] [DEBUG] default - 服务启动成功
[2023-03-16T23:06:34.425] [DEBUG] default - 服务启动成功
[2023-03-16T23:07:03.934] [DEBUG] default - 服务启动成功
[2023-03-16T23:07:27.136] [DEBUG] default - 服务启动成功
[2023-03-16T23:07:47.025] [DEBUG] default - 服务启动成功
[2023-03-16T23:11:47.761] [DEBUG] default - 服务启动成功
[2023-03-16T23:12:00.476] [DEBUG] default - 服务启动成功
[2023-03-16T23:12:34.211] [DEBUG] default - 服务启动成功
[2023-03-16T23:13:46.895] [DEBUG] default - 服务启动成功
[2023-03-16T23:15:46.214] [DEBUG] default - 服务启动成功
[2023-03-16T23:16:41.355] [DEBUG] default - 服务启动成功
[2023-03-16T23:17:07.262] [DEBUG] default - 服务启动成功
[2023-03-16T23:17:56.394] [DEBUG] default - 未知错误 TypeError: Cannot read properties of undefined (reading 'findOne')
    at findOne (/Users/hanhongguang/Documents/个人项目/Financial/src/mapper/index.js:83:9)
    at getType (/Users/hanhongguang/Documents/个人项目/Financial/src/mapper/budget/index.js:44:12)
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/newfinancialrecord.js:18:46)
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/controller/budget/newfinancialrecord.js:14:22)
    at /Users/hanhongguang/Documents/个人项目/Financial/src/router/budget/index.js:25:58
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:42:32)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:425:16
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:42:32)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:430:31)
[2023-03-16T23:19:08.222] [DEBUG] default - 服务启动成功
[2023-03-16T23:19:12.715] [DEBUG] default - 未知错误 TypeError: Cannot read properties of undefined (reading 'findOne')
    at findOne (/Users/hanhongguang/Documents/个人项目/Financial/src/mapper/index.js:83:9)
    at getType (/Users/hanhongguang/Documents/个人项目/Financial/src/mapper/budget/index.js:45:12)
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/newfinancialrecord.js:18:46)
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/controller/budget/newfinancialrecord.js:14:22)
    at /Users/hanhongguang/Documents/个人项目/Financial/src/router/budget/index.js:25:58
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:42:32)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:425:16
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:42:32)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:430:31)
[2023-03-16T23:21:43.481] [DEBUG] default - 服务启动成功
[2023-03-16T23:21:44.365] [DEBUG] default - 未知错误 TypeError: Cannot destructure property 'incometypename' of '(intermediate value)' as it is undefined.
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/newfinancialrecord.js:18:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/controller/budget/newfinancialrecord.js:14:16)
    at async /Users/hanhongguang/Documents/个人项目/Financial/src/router/budget/index.js:25:3
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9)
[2023-03-16T23:22:19.608] [DEBUG] default - 服务启动成功
[2023-03-16T23:22:20.165] [DEBUG] default - 服务启动成功
[2023-03-16T23:23:20.341] [DEBUG] default - 服务启动成功
[2023-03-16T23:23:57.552] [DEBUG] default - 服务启动成功
[2023-03-16T23:24:04.076] [DEBUG] default - 未知错误 TypeError: Cannot destructure property 'incomename' of '(intermediate value)' as it is null.
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/newfinancialrecord.js:18:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/controller/budget/newfinancialrecord.js:14:16)
    at async /Users/hanhongguang/Documents/个人项目/Financial/src/router/budget/index.js:25:3
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9)
[2023-03-16T23:25:42.168] [DEBUG] default - 服务启动成功
[2023-03-16T23:25:44.073] [DEBUG] default - 未知错误 TypeError: Cannot destructure property 'incomename' of '(intermediate value)' as it is null.
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/newfinancialrecord.js:18:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/controller/budget/newfinancialrecord.js:14:16)
    at async /Users/hanhongguang/Documents/个人项目/Financial/src/router/budget/index.js:25:3
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9)
[2023-03-18T17:36:25.769] [DEBUG] default - 服务启动成功
[2023-03-18T17:36:56.372] [DEBUG] default - 服务启动成功
[2023-03-18T17:37:17.331] [DEBUG] default - 服务启动成功
[2023-03-18T17:37:38.412] [DEBUG] default - 服务启动成功
[2023-03-18T17:37:53.188] [DEBUG] default - 服务启动成功
[2023-03-18T17:38:44.205] [DEBUG] default - 服务启动成功
[2023-03-18T17:38:54.015] [DEBUG] default - 服务启动成功
[2023-03-18T17:38:54.518] [DEBUG] default - 服务启动成功
[2023-03-18T17:40:27.241] [DEBUG] default - 服务启动成功
[2023-03-18T17:42:03.579] [DEBUG] default - 服务启动成功
[2023-03-18T17:42:55.564] [DEBUG] default - 服务启动成功
[2023-03-18T17:43:21.083] [DEBUG] default - 服务启动成功
[2023-03-18T17:43:27.762] [DEBUG] default - 服务启动成功
[2023-03-18T17:44:55.660] [DEBUG] default - 服务启动成功
[2023-03-18T17:45:06.566] [DEBUG] default - 服务启动成功
[2023-03-18T17:45:06.903] [DEBUG] default - 服务启动成功
[2023-03-18T17:45:07.434] [DEBUG] default - 服务启动成功
[2023-03-18T17:45:33.415] [DEBUG] default - 服务启动成功
[2023-03-18T17:45:39.365] [DEBUG] default - 服务启动成功
[2023-03-18T17:49:50.782] [DEBUG] default - 服务启动成功
[2023-03-18T17:51:44.857] [DEBUG] default - 服务启动成功
[2023-03-18T17:52:40.444] [DEBUG] default - 服务启动成功
[2023-03-18T17:53:08.503] [DEBUG] default - 服务启动成功
[2023-03-18T17:54:28.605] [DEBUG] default - 服务启动成功
[2023-03-18T17:54:37.615] [DEBUG] default - 服务启动成功
[2023-03-18T17:56:15.210] [DEBUG] default - 服务启动成功
[2023-03-18T17:57:11.567] [DEBUG] default - 服务启动成功
[2023-03-18T17:58:26.304] [DEBUG] default - 服务启动成功
[2023-03-18T17:58:59.094] [DEBUG] default - 服务启动成功
[2023-03-18T17:59:25.914] [DEBUG] default - 服务启动成功
[2023-03-18T18:00:15.492] [DEBUG] default - 服务启动成功
[2023-03-18T18:00:16.233] [DEBUG] default - 服务启动成功
[2023-03-18T18:00:27.305] [DEBUG] default - 服务启动成功
[2023-03-18T18:00:40.778] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa/lib/context.js:97:11)
    at jwt (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:66:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9) {
  originalError: TokenExpiredError: jwt expired
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:190:21
      at getSecret (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:97:14)
      at Object.module.exports [as verify] (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:101:10)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/verify.js:5:13
      at new Promise (<anonymous>)
      at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/verify.js:4:12)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:38:64
      at Array.map (<anonymous>)
      at jwt (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:38:43)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-unless/index.js:29:12 {
    expiredAt: 2023-03-16T18:27:35.000Z
  }
}
[2023-03-18T18:01:12.324] [DEBUG] default - 未知错误 Error: 方法没有实现
    at Object.methodNotAllowed (/Users/hanhongguang/Documents/个人项目/Financial/src/router/index.js:46:40)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:520:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 405,
    payload: { statusCode: 405, error: 'Method Not Allowed', message: '方法没有实现' },
    headers: {}
  }
}
[2023-03-18T18:01:27.727] [DEBUG] default - 服务启动成功
[2023-03-18T18:01:46.228] [DEBUG] default - 服务启动成功
[2023-03-18T18:02:05.719] [DEBUG] default - 服务启动成功
[2023-03-18T18:02:33.860] [DEBUG] default - 服务启动成功
[2023-03-18T18:02:46.201] [DEBUG] default - 服务启动成功
[2023-03-18T18:05:18.643] [DEBUG] default - 服务启动成功
[2023-03-18T18:05:56.208] [DEBUG] default - 服务启动成功
[2023-03-18T18:06:07.336] [DEBUG] default - 服务启动成功
[2023-03-18T18:06:26.814] [DEBUG] default - 服务启动成功
[2023-03-18T19:14:47.491] [DEBUG] default - 服务启动成功
[2023-03-18T19:14:54.129] [DEBUG] default - 服务启动成功
[2023-03-18T19:15:02.027] [DEBUG] default - 服务启动成功
[2023-03-18T19:15:02.652] [DEBUG] default - 服务启动成功
[2023-03-18T19:15:14.794] [DEBUG] default - 服务启动成功
[2023-03-18T19:16:37.448] [DEBUG] default - 服务启动成功
[2023-03-18T19:16:37.959] [DEBUG] default - 服务启动成功
[2023-03-18T19:17:13.955] [DEBUG] default - 服务启动成功
[2023-03-18T19:46:35.578] [DEBUG] default - 服务启动成功
[2023-03-18T19:47:06.364] [DEBUG] default - 服务启动成功
[2023-03-18T19:47:18.555] [DEBUG] default - 服务启动成功
[2023-03-18T19:47:45.645] [DEBUG] default - 服务启动成功
[2023-03-18T19:48:14.567] [DEBUG] default - 服务启动成功
[2023-03-18T19:49:55.684] [DEBUG] default - 服务启动成功
[2023-03-18T19:50:47.344] [DEBUG] default - 服务启动成功
[2023-03-18T19:51:35.460] [DEBUG] default - 未知错误 Error: 方法没有实现
    at Object.methodNotAllowed (/Users/hanhongguang/Documents/个人项目/Financial/src/router/index.js:46:40)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:520:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 405,
    payload: { statusCode: 405, error: 'Method Not Allowed', message: '方法没有实现' },
    headers: {}
  }
}
[2023-03-18T19:53:08.671] [DEBUG] default - 服务启动成功
[2023-03-18T19:53:47.161] [DEBUG] default - 服务启动成功
[2023-03-18T19:54:09.658] [DEBUG] default - 服务启动成功
[2023-03-18T19:54:13.276] [DEBUG] default - 未知错误 Error: 方法没有实现
    at Object.methodNotAllowed (/Users/hanhongguang/Documents/个人项目/Financial/src/router/index.js:46:40)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:520:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 405,
    payload: { statusCode: 405, error: 'Method Not Allowed', message: '方法没有实现' },
    headers: {}
  }
}
[2023-03-18T19:54:36.589] [DEBUG] default - 服务启动成功
[2023-03-18T19:55:08.710] [DEBUG] default - 未知错误 ReferenceError: reuqire is not defined
    at Object.<anonymous> (/Users/hanhongguang/Documents/个人项目/Financial/src/controller/budget/getbalancepayments.js:9:15)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/hanhongguang/Documents/个人项目/Financial/src/router/budget/index.js:13:9
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:42:32)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:425:16
[2023-03-18T19:55:18.770] [DEBUG] default - 服务启动成功
[2023-03-18T19:55:50.422] [DEBUG] default - 服务启动成功
[2023-03-18T19:56:00.368] [DEBUG] default - 服务启动成功
[2023-03-18T19:56:04.462] [DEBUG] default - 服务启动成功
[2023-03-18T19:58:33.452] [DEBUG] default - 服务启动成功
[2023-03-18T20:03:18.131] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa/lib/context.js:97:11)
    at jwt (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:66:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9) {
  originalError: TokenExpiredError: jwt expired
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:190:21
      at getSecret (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:97:14)
      at Object.module.exports [as verify] (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:101:10)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/verify.js:5:13
      at new Promise (<anonymous>)
      at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/verify.js:4:12)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:38:64
      at Array.map (<anonymous>)
      at jwt (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:38:43)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-unless/index.js:29:12 {
    expiredAt: 2023-03-15T19:22:14.000Z
  }
}
[2023-03-18T20:05:28.628] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa/lib/context.js:97:11)
    at jwt (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:66:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9) {
  originalError: TokenExpiredError: jwt expired
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:190:21
      at getSecret (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:97:14)
      at Object.module.exports [as verify] (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:101:10)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/verify.js:5:13
      at new Promise (<anonymous>)
      at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/verify.js:4:12)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:38:64
      at Array.map (<anonymous>)
      at jwt (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:38:43)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-unless/index.js:29:12 {
    expiredAt: 2023-03-16T17:49:19.000Z
  }
}
[2023-03-18T20:06:20.173] [DEBUG] default - 服务启动成功
[2023-03-18T20:06:28.939] [DEBUG] default - 服务启动成功
[2023-03-18T20:07:52.511] [DEBUG] default - 服务启动成功
[2023-03-18T20:08:10.369] [DEBUG] default - 服务启动成功
[2023-03-18T20:08:13.393] [DEBUG] default - 服务启动成功
[2023-03-18T20:09:14.394] [DEBUG] default - 服务启动成功
[2023-03-18T20:10:07.320] [DEBUG] default - 服务启动成功
[2023-03-18T20:10:11.035] [DEBUG] default - 服务启动成功
[2023-03-18T20:10:27.472] [DEBUG] default - 服务启动成功
[2023-03-18T20:10:55.761] [DEBUG] default - 服务启动成功
[2023-03-18T20:10:59.938] [DEBUG] default - 服务启动成功
[2023-03-18T20:11:06.358] [DEBUG] default - 服务启动成功
[2023-03-18T20:11:09.930] [DEBUG] default - 服务启动成功
[2023-03-18T20:11:33.825] [DEBUG] default - 服务启动成功
[2023-03-18T20:12:21.062] [DEBUG] default - 服务启动成功
[2023-03-18T20:12:25.930] [DEBUG] default - 服务启动成功
[2023-03-18T20:12:27.050] [DEBUG] default - 服务启动成功
[2023-03-18T20:16:12.136] [DEBUG] default - 服务启动成功
[2023-03-18T20:16:43.420] [DEBUG] default - 服务启动成功
[2023-03-18T20:17:29.132] [DEBUG] default - 服务启动成功
[2023-03-18T20:17:47.259] [DEBUG] default - 服务启动成功
[2023-03-18T20:18:19.435] [DEBUG] default - 服务启动成功
[2023-03-18T20:18:34.708] [DEBUG] default - 服务启动成功
[2023-03-18T20:18:48.613] [DEBUG] default - 服务启动成功
[2023-03-18T20:19:24.970] [DEBUG] default - 服务启动成功
[2023-03-18T20:19:28.656] [DEBUG] default - 服务启动成功
[2023-03-18T20:22:07.586] [DEBUG] default - 服务启动成功
[2023-03-18T20:22:13.177] [DEBUG] default - 服务启动成功
[2023-03-18T20:24:35.130] [DEBUG] default - 服务启动成功
[2023-03-18T20:25:20.355] [DEBUG] default - 服务启动成功
[2023-03-18T20:25:39.368] [DEBUG] default - 服务启动成功
[2023-03-18T20:26:01.291] [DEBUG] default - 服务启动成功
[2023-03-18T20:26:09.247] [DEBUG] default - 服务启动成功
[2023-03-18T20:26:34.991] [DEBUG] default - 服务启动成功
[2023-03-18T20:26:49.453] [DEBUG] default - 服务启动成功
[2023-03-18T20:27:07.002] [DEBUG] default - 服务启动成功
[2023-03-18T20:28:17.421] [DEBUG] default - 服务启动成功
[2023-03-18T20:29:13.177] [DEBUG] default - 服务启动成功
[2023-03-18T20:29:26.731] [DEBUG] default - 服务启动成功
[2023-03-18T20:29:44.197] [DEBUG] default - 服务启动成功
[2023-03-19T19:33:05.683] [DEBUG] default - 服务启动成功
[2023-03-19T19:36:04.108] [DEBUG] default - 服务启动成功
[2023-03-19T19:36:04.620] [DEBUG] default - 服务启动成功
[2023-03-19T19:36:52.221] [DEBUG] default - 服务启动成功
[2023-03-19T19:37:35.160] [DEBUG] default - 服务启动成功
[2023-03-19T19:38:05.399] [DEBUG] default - 服务启动成功
[2023-03-19T19:38:27.997] [DEBUG] default - 服务启动成功
[2023-03-19T19:38:40.910] [DEBUG] default - 服务启动成功
[2023-03-19T19:38:48.347] [DEBUG] default - 服务启动成功
[2023-03-19T19:38:52.891] [DEBUG] default - 服务启动成功
[2023-03-19T19:41:09.532] [DEBUG] default - 服务启动成功
[2023-03-19T19:41:46.768] [DEBUG] default - 服务启动成功
[2023-03-19T19:42:01.798] [DEBUG] default - 服务启动成功
[2023-03-19T19:42:23.806] [DEBUG] default - 服务启动成功
[2023-03-19T19:43:03.500] [DEBUG] default - 服务启动成功
[2023-03-19T19:43:19.681] [DEBUG] default - 服务启动成功
[2023-03-19T19:43:40.635] [DEBUG] default - 服务启动成功
[2023-03-19T19:44:29.584] [DEBUG] default - 服务启动成功
[2023-03-19T19:44:47.421] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa/lib/context.js:97:11)
    at jwt (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:66:26)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9) {
  originalError: TokenExpiredError: jwt expired
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:190:21
      at getSecret (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:97:14)
      at Object.module.exports [as verify] (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:101:10)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/verify.js:5:13
      at new Promise (<anonymous>)
      at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/verify.js:4:12)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:38:64
      at Array.map (<anonymous>)
      at jwt (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:38:43)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-unless/index.js:29:12 {
    expiredAt: 2023-03-18T16:03:21.000Z
  }
}
[2023-03-19T19:46:05.144] [DEBUG] default - 服务启动成功
[2023-03-19T19:46:06.088] [DEBUG] default - 服务启动成功
[2023-03-19T19:46:50.367] [DEBUG] default - 服务启动成功
[2023-03-19T19:47:08.893] [DEBUG] default - 服务启动成功
[2023-03-19T19:47:18.419] [DEBUG] default - 服务启动成功
[2023-03-19T19:48:44.972] [DEBUG] default - 服务启动成功
[2023-03-19T19:48:49.137] [DEBUG] default - 服务启动成功
[2023-03-19T19:48:53.105] [DEBUG] default - 服务启动成功
[2023-03-19T19:48:56.765] [DEBUG] default - 服务启动成功
[2023-03-19T19:49:08.557] [DEBUG] default - 服务启动成功
[2023-03-19T19:49:18.651] [DEBUG] default - 服务启动成功
[2023-03-19T19:49:32.543] [DEBUG] default - 服务启动成功
[2023-03-19T19:49:33.374] [DEBUG] default - 服务启动成功
[2023-03-19T19:49:47.781] [DEBUG] default - 服务启动成功
[2023-03-19T19:49:53.227] [DEBUG] default - 服务启动成功
[2023-03-19T19:49:54.073] [DEBUG] default - 服务启动成功
[2023-03-19T19:50:11.016] [DEBUG] default - 服务启动成功
[2023-03-19T19:51:21.093] [DEBUG] default - 服务启动成功
[2023-03-19T19:51:28.631] [DEBUG] default - 服务启动成功
[2023-03-19T19:52:36.790] [DEBUG] default - 服务启动成功
[2023-03-19T19:52:50.209] [DEBUG] default - 服务启动成功
[2023-03-19T19:53:06.240] [DEBUG] default - 服务启动成功
[2023-03-19T19:54:05.200] [DEBUG] default - 服务启动成功
[2023-03-19T19:55:10.870] [DEBUG] default - 服务启动成功
[2023-03-19T19:55:15.615] [DEBUG] default - 服务启动成功
[2023-03-19T19:55:26.057] [DEBUG] default - 服务启动成功
[2023-03-19T19:55:33.256] [DEBUG] default - 服务启动成功
[2023-03-19T20:00:20.111] [DEBUG] default - 服务启动成功
[2023-03-19T20:02:20.855] [DEBUG] default - 服务启动成功
[2023-03-19T20:02:26.014] [DEBUG] default - code:401 UnauthorizedError: Authentication Error
    at Object.throw (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa/lib/context.js:97:11)
    at jwt (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:66:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9) {
  originalError: TokenExpiredError: jwt expired
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:190:21
      at getSecret (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:97:14)
      at Object.module.exports [as verify] (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/jsonwebtoken/verify.js:101:10)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/verify.js:5:13
      at new Promise (<anonymous>)
      at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/verify.js:4:12)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:38:64
      at Array.map (<anonymous>)
      at jwt (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-jwt/lib/index.js:38:43)
      at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-unless/index.js:29:12 {
    expiredAt: 2023-03-18T14:00:52.000Z
  }
}
[2023-03-19T20:03:23.730] [DEBUG] default - 服务启动成功
[2023-03-19T20:03:30.965] [DEBUG] default - 服务启动成功
[2023-03-19T20:04:27.827] [DEBUG] default - 服务启动成功
[2023-03-19T20:04:50.326] [DEBUG] default - 服务启动成功
[2023-03-19T20:04:56.003] [DEBUG] default - 服务启动成功
[2023-03-19T20:10:25.719] [DEBUG] default - 服务启动成功
[2023-03-19T20:10:38.907] [DEBUG] default - 服务启动成功
[2023-03-19T20:10:54.499] [DEBUG] default - 服务启动成功
[2023-03-19T20:10:58.425] [DEBUG] default - 未知错误 ReferenceError: _id is not defined
    at getimportrecords (/Users/hanhongguang/Documents/个人项目/Financial/src/mapper/budget/index.js:56:96)
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/getimportrecords.js:12:26)
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/controller/budget/getimportrecords.js:11:20)
    at /Users/hanhongguang/Documents/个人项目/Financial/src/router/budget/index.js:33:56
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:42:32)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:425:16
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:42:32)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:430:31)
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:42:32)
[2023-03-19T20:11:29.154] [DEBUG] default - 服务启动成功
[2023-03-19T20:11:48.066] [DEBUG] default - 服务启动成功
[2023-03-19T20:12:54.824] [DEBUG] default - 服务启动成功
[2023-03-19T20:12:57.538] [DEBUG] default - 未知错误 TypeError: find(...).aggregate is not a function
    at getimportrecords (/Users/hanhongguang/Documents/个人项目/Financial/src/mapper/budget/index.js:56:90)
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/getimportrecords.js:12:26)
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/controller/budget/getimportrecords.js:11:20)
    at /Users/hanhongguang/Documents/个人项目/Financial/src/router/budget/index.js:33:56
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:42:32)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:425:16
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:42:32)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:430:31)
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:42:32)
[2023-03-19T20:13:32.292] [DEBUG] default - 服务启动成功
[2023-03-19T20:14:00.437] [DEBUG] default - 服务启动成功
[2023-03-19T20:15:13.572] [DEBUG] default - 服务启动成功
[2023-03-19T20:15:29.631] [DEBUG] default - 服务启动成功
[2023-03-19T20:15:46.970] [DEBUG] default - 服务启动成功
[2023-03-19T20:16:00.114] [DEBUG] default - 服务启动成功
[2023-03-19T20:16:15.626] [DEBUG] default - 服务启动成功
[2023-03-19T20:16:27.228] [DEBUG] default - 服务启动成功
[2023-03-19T20:16:28.315] [DEBUG] default - 未知错误 ReferenceError: _id is not defined
    at getimportrecords (/Users/hanhongguang/Documents/个人项目/Financial/src/mapper/budget/index.js:56:85)
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/getimportrecords.js:12:26)
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/controller/budget/getimportrecords.js:11:20)
    at /Users/hanhongguang/Documents/个人项目/Financial/src/router/budget/index.js:33:56
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:42:32)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:425:16
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:42:32)
    at /Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/@koa/router/lib/router.js:430:31)
    at dispatch (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-compose/index.js:42:32)
[2023-03-19T20:19:23.664] [DEBUG] default - 服务启动成功
[2023-03-19T20:19:27.973] [DEBUG] default - 服务启动成功
[2023-03-19T20:19:32.426] [DEBUG] default - 服务启动成功
[2023-03-19T20:19:37.190] [DEBUG] default - 服务启动成功
[2023-03-19T20:19:39.619] [DEBUG] default - 服务启动成功
[2023-03-19T20:19:47.118] [DEBUG] default - 服务启动成功
[2023-03-19T20:19:55.417] [DEBUG] default - 服务启动成功
[2023-03-19T20:27:40.447] [DEBUG] default - 服务启动成功
[2023-03-19T20:27:42.550] [DEBUG] default - 服务启动成功
[2023-03-19T20:29:20.438] [DEBUG] default - 服务启动成功
[2023-03-19T20:29:34.083] [DEBUG] default - 服务启动成功
[2023-03-19T20:29:35.122] [DEBUG] default - 未知错误 TypeError: Found non-callable @@iterator
    at /Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/getimportrecords.js:17:13
    at Array.forEach (<anonymous>)
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/getimportrecords.js:15:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/controller/budget/getimportrecords.js:11:14)
    at async /Users/hanhongguang/Documents/个人项目/Financial/src/router/budget/index.js:33:3
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9)
[2023-03-19T20:30:06.389] [DEBUG] default - 服务启动成功
[2023-03-19T20:30:14.121] [DEBUG] default - 服务启动成功
[2023-03-19T20:30:15.618] [DEBUG] default - 未知错误 TypeError: Found non-callable @@iterator
    at /Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/getimportrecords.js:17:10
    at Array.forEach (<anonymous>)
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/getimportrecords.js:15:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/controller/budget/getimportrecords.js:11:14)
    at async /Users/hanhongguang/Documents/个人项目/Financial/src/router/budget/index.js:33:3
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9)
[2023-03-19T20:30:23.848] [DEBUG] default - 服务启动成功
[2023-03-19T20:30:24.755] [DEBUG] default - 未知错误 SyntaxError: Unexpected token _ in JSON at position 4
    at JSON.parse (<anonymous>)
    at /Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/getimportrecords.js:18:10
    at Array.forEach (<anonymous>)
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/getimportrecords.js:15:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/controller/budget/getimportrecords.js:11:14)
    at async /Users/hanhongguang/Documents/个人项目/Financial/src/router/budget/index.js:33:3
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9)
[2023-03-19T20:30:53.499] [DEBUG] default - 服务启动成功
[2023-03-19T20:30:54.438] [DEBUG] default - 未知错误 TypeError: Found non-callable @@iterator
    at /Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/getimportrecords.js:19:13
    at Array.forEach (<anonymous>)
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/getimportrecords.js:15:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/controller/budget/getimportrecords.js:11:14)
    at async /Users/hanhongguang/Documents/个人项目/Financial/src/router/budget/index.js:33:3
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9)
[2023-03-19T20:31:05.463] [DEBUG] default - 服务启动成功
[2023-03-19T20:31:06.675] [DEBUG] default - 未知错误 TypeError: Found non-callable @@iterator
    at /Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/getimportrecords.js:20:13
    at Array.forEach (<anonymous>)
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/getimportrecords.js:15:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/controller/budget/getimportrecords.js:11:14)
    at async /Users/hanhongguang/Documents/个人项目/Financial/src/router/budget/index.js:33:3
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9)
[2023-03-19T20:31:43.123] [DEBUG] default - 服务启动成功
[2023-03-19T20:31:43.806] [DEBUG] default - 未知错误 TypeError: Found non-callable @@iterator
    at /Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/getimportrecords.js:18:13
    at Array.forEach (<anonymous>)
    at module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/service/budget/getimportrecords.js:15:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Users/hanhongguang/Documents/个人项目/Financial/src/controller/budget/getimportrecords.js:11:14)
    at async /Users/hanhongguang/Documents/个人项目/Financial/src/router/budget/index.js:33:3
    at async bodyParser (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa-bodyparser/index.js:95:5)
    at async cors (/Users/hanhongguang/Documents/个人项目/Financial/node_modules/koa2-cors/dist/index.js:91:9)
[2023-03-19T20:31:50.559] [DEBUG] default - 服务启动成功
[2023-03-19T20:31:58.218] [DEBUG] default - 服务启动成功
[2023-03-19T20:32:16.090] [DEBUG] default - 服务启动成功
[2023-03-19T20:32:20.212] [DEBUG] default - 服务启动成功
[2023-03-19T20:33:07.341] [DEBUG] default - 服务启动成功
[2023-03-19T20:33:18.611] [DEBUG] default - 服务启动成功
[2023-03-19T20:34:23.373] [DEBUG] default - 服务启动成功
[2023-03-19T20:34:33.039] [DEBUG] default - 服务启动成功
[2023-03-19T20:34:39.623] [DEBUG] default - 服务启动成功
[2023-03-19T20:34:43.430] [DEBUG] default - 服务启动成功
[2023-03-19T20:34:49.497] [DEBUG] default - 服务启动成功
[2023-03-19T20:36:06.323] [DEBUG] default - 服务启动成功
